### ISSUE TITLE
Possible Kafka message size issues

### ISSUE THREAD

**Issue by ibaldin** [fabric-testbed/ControlFramework#170] opened 2022-02-25 18:44 UTC
With a large number of slices (upwards of 30) Paul encountered an issue 
```
I’m getting a lot of ” Status.INVALID_ARGUMENTS, Invalid arguments” in cases that used to work reliably.
```
and
```
I think there are two separate issues with that made it so my get slices requests were failing.  One  is simply that if you have too many slices, get_slices takes a very, very, very long time.  The other seems to be that if I try to run things from two different locations (i.e. my laptop and jupyter hub), there are can be errors (timeout, and “invalid argument” exceptions).   I think the extended time it takes to retrieve a lot of slices makes the concurrent request error likely (i.e. the race condition opportunity is longer and more likely to be hit). (edited) 

FYI 30 slices caused it.  I’m currently trying to re-write the tests to be one big slice.
```

This is possibly a Kafka message size issue in which case we may have a near- and a longer-term set of fixes we need to think about:
1. Enable compression (turn it on in 1.2)
2. See if some of the API calls (list slices e.g.) need to be redesigned to allow pagination of results (Beyond 1.2)

**Comment by kthare10** [comment] 2022-02-27 17:55
Root Cause:

Issue has been introduced by adding the support to return error messages for each reservation/sliver within a slice in the get_slice response. So a get_slices query not only queries the Slices table, but also results in a query of reservations (failed, closing, close wait) for each slice to grab the error and return it back. So when you have lot of slices with each slice have lots of reservations. 

Proposed Solution:
- Remove the per sliver error messages from get_slices()
- Add an additional field in ReservationInfo field called error_message
class ReservationInfo(JSONField):
    """
    Reservation info structure for ASM sliver objects
    """

    def __init__(self, **kwargs):
        self.reservation_id = None
        self.reservation_state = None
        self.error_message = None
        self._set_fields(**kwargs)
- Update the ASM to reflect the error along with reservation id and state
- User can grab the required errors from the get_slice_topology() API instead of get_slices()
 
Example of the Sliver from ASM:
Node:
   Site              : UKYY
   Type              : VM
   Management IP     : None
   Capaciy Hints     : None
   Location          : None
   Components        : {'node-0-nic1': {'details': 'Mellanox ConnectX-6 VPI MCX653 dual port 100Gbps', 'model': 'ConnectX-6', 'name': 'node-0-nic1', 'type': 'SharedNIC'}}
   Interface         : {'node-0-nic1-p1': {'capacities': '{ unit: 1 }', 'labels': '{ local_name: p1}', 'name': 'node-0-nic1-p1', 'type': 'SharedPort'}}
   Sliver            : {'capacities': '{ core: 2 , ram: 6 G, disk: 10 G}', 'image_ref': 'default_centos_8', 'image_type': 'qcow2', 'name': 'node-0', 'reservation_info': '{"error_message": "Insufficient resources: No candidates nodes found to serve res: #f560350a-8bcc-408a-a4e4-47a52ebd21de slice: [Slice-comps-only-199(d1ca283b-2421-4857-a69c-437d072ad645) Owner:[kthare10@email.unc.edu](mailto:kthare10@email.unc.edu)] state:[Nascent,Ticketing] ", "reservation_id": "f560350a-8bcc-408a-a4e4-47a52ebd21de", "reservation_state": "Closed"}', 'site': 'UKYY', 'type': 'VM'}
 
Long Term:
- Need to add support for pagination in get_slices() API
- Also, we need to also limit the number of closed/dead slices to be retained
- Return always StableOK, StableError, Configuring slices by default in get_slices() API and only return Dead and Closing slices when explicitly asked
 
I tested the proposed solution above on DEV and used Paul’s notebook to create 200 slices each with 10 slivers. I did not run into any Gateway Timeout Failures.

**Closed** 2022-09-01 13:29 UTC
Labels: bug, 1.2, 1.3
